# Generated by Django 6.1 on 2026-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
